spring:
  application:
    name: aluno-ms
  server:
    port: 8001

# Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
  username: sa
  password:

  h2:
    console:
      enabled: true
      path: /h2-console


